#pragma once
#include <iostream>
#include <SFML/Audio.hpp>
#include <SFML/Graphics.hpp>
#include <thread>
#include <memory>
#include <mutex>
#include <atomic>
#include <chrono>
#include <optional>
#include <vector>
#include <string>
#include <entt/entt.hpp>
#include <TGUI/TGUI.hpp>
#include <TGUI/Backend/SFML-Graphics.hpp>


//// Segues
//#include <swoosh/Segues/BlackWashFade.h>
//#include <swoosh/Segues/BlendFadeIn.h>
//#include <swoosh/Segues/BlurFadeIn.h>
//#include <swoosh/Segues/Checkerboard.h>
//#include <swoosh/Segues/CircleClose.h>
////#include <swoosh\Swoosh/Segues/CircleOpen.h>
//#include <swoosh/Segues/CrossZoom.h>
//#include <swoosh/Segues/Cube3D.h>
//#include <swoosh/Segues/DiamondTileCircle.h>
//#include <swoosh/Segues/DiamondTileSwipe.h>
//#include <swoosh/Segues/Dream.h>
//#include <swoosh/Segues/HorizontalOpen.h>
//#include <swoosh/Segues/HorizontalSlice.h>
//#include <swoosh/Segues/Morph.h>
//#include <swoosh/Segues/PageTurn.h>
//#include <swoosh/Segues/PixelateBlackWashFade.h>
//#include <swoosh/Segues/PushIn.h>
//#include <swoosh/Segues/RadialCCW.h>
//#include <swoosh/Segues/RetroBlit.h>
//#include <swoosh/Segues/SlideIn.h>
//#include <swoosh/Segues/SwipeIn.h>
//#include <swoosh/Segues/VerticalOpen.h>
//#include <swoosh/Segues/VerticalSlice.h>
//#include <swoosh/Segues/WhiteWashFade.h>
//#include <swoosh/Segues/ZoomFadeIn.h>
//#include <swoosh/Segues/ZoomFadeInBounce.h>
//#include <swoosh/Segues/ZoomIn.h>
//#include <swoosh/Segues/ZoomOut.h>
//
//// Core swoosh
//#include <swoosh/Swoosh/ActionList.h>
//#include <swoosh/Swoosh/Activity.h>
//#include <swoosh/Swoosh/ActivityController.h>
//#include <swoosh/Swoosh/Ease.h>
//#include <swoosh/Swoosh/EmbedGLSL.h>
//#include <swoosh/Swoosh/Game.h>
//#include <swoosh/Swoosh/Segue.h>
//#include <swoosh/Swoosh/Shaders.h>
//#include <swoosh/Swoosh/Timer.h>
